language: node_js
node_js:
  - "13"

cache: yarn

install: yarn

jobs:
  include:
    - stage: build
      script: 
        - yarn lint
        - yarn test
    - stage: npm release
      if: tag IS present
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_API_TOKEN"
        cleanup: true
        on:
          tags: true